### ISSUE TITLE
Justin: week 9 video

### ISSUE THREAD

**Issue by yolandayangg** [yolandayangg/m223coders#17]
[Video link](https://youtu.be/DM4fRFJ2Jg0)

**Comment by jm1021** [comment]
Justin, I was very pleased to see this video.  It is very positive step.   You seem to have some understanding of how to contribute to project.   6/6 for the effort

In the remaining two points, there are many thing that I could consider for improvement:
1. Being in a position of working with others, so that you could push code
2. Working from objectives that you and Scrum Team have agreed are important
3. Better at commenting on everyone's project

1.5/2
